class PinConfig:
    PIN_TEMP_HUMIDITY_INSIDE = 21
    PIN_TEMP_HUMIDITY_OUTSIDE = 20
    
    PIN_FAN_POWER = 27
    
    PIN_PUMP_POWER = None
    
    PIN_VALVE_1_POWER = 18
    PIN_VALVE_2_POWER = 15 # Works, pepper bed
    PIN_VALVE_3_POWER = 23 

    PIN_VALVE_4_POWER = None
    PIN_VALVE_5_POWER = None
    PIN_VALVE_6_POWER = None
    PIN_VALVE_7_POWER = None
    PIN_VALVE_8_POWER = None
    PIN_VALVE_9_POWER = None
    
    PIN_CIRC_FAN_POWER = 22
    
    PIN_WINDOW_SE_INPUT_A = 25
    PIN_WINDOW_SE_INPUT_B = 8
    PIN_WINDOW_N_INPUT_A = 5
    PIN_WINDOW_N_INPUT_B = 6
    PIN_WINDOW_SW_INPUT_A = 26
    PIN_WINDOW_SW_INPUT_B = 19
    PIN_WINDOW_E_INPUT_A = 9
    PIN_WINDOW_E_INPUT_B = 10
    
